export enum MultipleEvents {
  CORRECT_ANSWER = "CORRECT_ANSWER",
  COMPLETELY_WRONG_ANSWER = "COMPLETELY_WRONG_ANSWER",
  SOME_WRONG_ANSWER = "SOME_WRONG_ANSWER",
  NO_ANSWER = "NO_ANSWER",
  FINISH = "FINISH",
}
